version: '3.8'

services:
    app-users:
        build:
            context: .
            dockerfile: docker/users-dockerfile
        container_name: users
        ports:
            - '${USERS_PORT}:${USERS_PORT}'
        env_file:
            - .env.docker
        volumes:
            - .:/app
            - /app/node_modules
            - /app/dist
            - ${HOME}/.aws:/root/.aws:ro
        depends_on:
            db-users-shard-1:
                condition: service_healthy
            db-users-shard-2:
                condition: service_healthy
            localstack:
                condition: service_healthy
        networks:
            - videonet
    app-videos:
        build:
            context: .
            dockerfile: docker/videos-dockerfile
        container_name: videos
        ports:
            - '${VIDEOS_PORT}:${VIDEOS_PORT}'
        env_file:
            - .env.docker
        volumes:
            - .:/app
            - /app/node_modules
            - /app/dist
            - ${HOME}/.aws:/root/.aws:ro
        depends_on:
            db-videos:
                condition: service_healthy
            localstack:
                condition: service_healthy
        networks:
            - videonet
    db-users-shard-1:
        image: postgres:15-alpine
        container_name: postgres-users-shard-1
        restart: unless-stopped
        environment:
            - POSTGRES_USER=${USERS_POSTGRES_DB_SHARD_1_USER}
            - POSTGRES_PASSWORD=${USERS_POSTGRES_DB_SHARD_1_PASSWORD}
            - POSTGRES_DB=${USERS_POSTGRES_DB_SHARD_1_NAME}
        ports:
            - '${USERS_POSTGRES_DB_SHARD_1_PORT}:${USERS_POSTGRES_DB_SHARD_1_PORT_INTERNAL}'
        volumes:
            - db_data_users_shard_1:/var/lib/postgresql/data
        networks:
            - videonet
        healthcheck:
            test:
                [
                    'CMD-SHELL',
                    'pg_isready -U ${USERS_POSTGRES_DB_SHARD_1_USER} -d ${USERS_POSTGRES_DB_SHARD_1_NAME} -h localhost || exit 1',
                ]
            interval: 5s
            timeout: 3s
            retries: 3
            start_period: 30s
    db-users-shard-2:
        image: postgres:15-alpine
        container_name: postgres-users-shard-2
        restart: unless-stopped
        environment:
            - POSTGRES_USER=${USERS_POSTGRES_DB_SHARD_2_USER}
            - POSTGRES_PASSWORD=${USERS_POSTGRES_DB_SHARD_2_PASSWORD}
            - POSTGRES_DB=${USERS_POSTGRES_DB_SHARD_2_NAME}
        ports:
            - '${USERS_POSTGRES_DB_SHARD_2_PORT}:${USERS_POSTGRES_DB_SHARD_2_PORT_INTERNAL}'
        volumes:
            - db_data_users_shard_2:/var/lib/postgresql/data
        networks:
            - videonet
        healthcheck:
            test:
                [
                    'CMD-SHELL',
                    'pg_isready -U ${USERS_POSTGRES_DB_SHARD_2_USER} -d ${USERS_POSTGRES_DB_SHARD_2_NAME} -h localhost || exit 1',
                ]
            interval: 5s
            timeout: 3s
            retries: 3
            start_period: 30s
    db-videos:
        image: postgres:15-alpine
        container_name: postgres-videos
        restart: unless-stopped
        environment:
            - POSTGRES_USER=${VIDEOS_POSTGRES_DB_USER}
            - POSTGRES_PASSWORD=${VIDEOS_POSTGRES_DB_PASSWORD}
            - POSTGRES_DB=${VIDEOS_POSTGRES_DB_NAME}
            - DB_REPLICA_USER=${VIDEOS_POSTGRES_DB_REPLICA_USER}
            - DB_REPLICA_PASSWORD=${VIDEOS_POSTGRES_DB_REPLICA_PASSWORD}
        ports:
            - '${VIDEOS_POSTGRES_DB_PORT}:${VIDEOS_POSTGRES_DB_PORT_INTERNAL}'
        volumes:
            - db_data_videos:/var/lib/postgresql/data
            - ./docker/postgres/replica-init.sh:/docker-entrypoint-initdb.d/replica-init.sh:ro
        networks:
            - videonet
        healthcheck:
            test:
                [
                    'CMD-SHELL',
                    'pg_isready -U ${VIDEOS_POSTGRES_DB_USER} -d ${VIDEOS_POSTGRES_DB_NAME} -h localhost || exit 1',
                ]
            interval: 5s
            timeout: 3s
            retries: 3
            start_period: 30s
    db-videos-replica:
        image: postgres:15-alpine
        container_name: postgres-videos-replica
        restart: unless-stopped
        environment:
            - POSTGRES_USER=${VIDEOS_POSTGRES_DB_REPLICA_USER}
            - POSTGRES_PASSWORD=${VIDEOS_POSTGRES_DB_REPLICA_PASSWORD}
            - DB_HOST=db-videos
            - DB_REPLICA_USER=${VIDEOS_POSTGRES_DB_REPLICA_USER}
            - DB_REPLICA_PASSWORD=${VIDEOS_POSTGRES_DB_REPLICA_PASSWORD}
            - PGDATA=/var/lib/postgresql/data/pgdata
        ports:
            - '${VIDEOS_POSTGRES_DB_REPLICA_PORT}:${VIDEOS_POSTGRES_DB_REPLICA_PORT_INTERNAL}'
        volumes:
            - db_data_videos_replica:/var/lib/postgresql/data/pgdata
            - ./docker/postgres/replica-setup.sh:/docker/replica-setup.sh:ro
        depends_on:
            db-videos:
                condition: service_healthy
        networks:
            - videonet
        command: ['/bin/sh', '-c', './docker/replica-setup.sh && docker-entrypoint.sh postgres']
        healthcheck:
            test: >
                CMD-SHELL
                pg_isready -U ${VIDEOS_POSTGRES_DB_REPLICA_USER} -d ${VIDEOS_POSTGRES_DB_NAME:-postgres} -h localhost &&
                psql -U ${VIDEOS_POSTGRES_DB_REPLICA_USER} -d ${VIDEOS_POSTGRES_DB_NAME:-postgres} \
                    -c 'SELECT pg_is_in_recovery()' | grep -q t
            interval: 5s
            timeout: 3s
            retries: 3
            start_period: 30s
    db-mongo-config-server:
        image: mongo:7.0
        container_name: db-mongo-config-server
        command: --configsvr --replSet configReplSet --port ${VIDEOS_COMMENT_MONGO_DB_CONFIG_SERVER_PORT} --bind_ip_all
        volumes:
            - db_mongo_config_server:/data/db
        networks:
            - videonet
        healthcheck:
            test: ['CMD', 'mongosh', '--eval', "db.adminCommand('ping')"]
            interval: 5s
            timeout: 3s
            retries: 10
    db-mongo-shard-1:
        image: mongo:7.0
        container_name: db-mongo-shard-1
        command: --shardsvr --replSet shard1ReplSet --port ${VIDEOS_COMMENT_MONGO_DB_SHARD_1_PORT} --bind_ip_all
        depends_on:
            - db-mongo-config-server
        volumes:
            - db_mongo_shard_1:/data/db
        networks:
            - videonet
        healthcheck:
            test: ['CMD', 'mongosh', '--eval', "db.adminCommand('ping')"]
            interval: 5s
            timeout: 3s
            retries: 10
    db-mongo-shard-2:
        image: mongo:7.0
        container_name: db-mongo-shard-2
        command: --shardsvr --replSet shard2ReplSet --port ${VIDEOS_COMMENT_MONGO_DB_SHARD_2_PORT} --bind_ip_all
        depends_on:
            - db-mongo-config-server
        volumes:
            - db_mongo_shard_2:/data/db
        networks:
            - videonet
        healthcheck:
            test: ['CMD', 'mongosh', '--eval', "db.adminCommand('ping')"]
            interval: 5s
            timeout: 3s
            retries: 10
    db-video-comments:
        image: mongo:7.0
        container_name: mongo-video-comments
        restart: unless-stopped
        depends_on:
            - db-mongo-config-server
            - db-mongo-shard-1
            - db-mongo-shard-2
        environment:
            - CONFIG_SERVER_HOST=${VIDEOS_COMMENT_CONFIG_SERVER_HOST}
            - CONFIG_SERVER_PORT=${VIDEOS_COMMENT_MONGO_DB_CONFIG_SERVER_PORT}
            - SHARD_1_HOST=${VIDEOS_COMMENT_MONGO_DB_SHARD_1_HOST}
            - SHARD_1_PORT=${VIDEOS_COMMENT_MONGO_DB_SHARD_1_PORT}
            - SHARD_2_HOST=${VIDEOS_COMMENT_MONGO_DB_SHARD_2_HOST}
            - SHARD_2_PORT=${VIDEOS_COMMENT_MONGO_DB_SHARD_2_PORT}
            - MONGOS_PORT=${VIDEOS_COMMENT_MONGO_DB_PORT}
            - MONGO_DB_NAME=${VIDEOS_COMMENT_MONGO_DB_NAME}
            - MONGO_COLLECTION_NAME=${VIDEOS_COMMENT_MONGO_DB_COLLECTION_NAME}
        ports:
            - '${VIDEOS_COMMENT_MONGO_DB_PORT_INTERNAL}:${VIDEOS_COMMENT_MONGO_DB_PORT}'
        volumes:
            - ./docker/mongo/mongo-init-rs.js:/mongo-init-rs.js:ro
            - ./docker/mongo/mongo-init-sharding.js:/mongo-init-sharding.js:ro
            - ./docker/mongo/mongo-wait-and-run.sh:/mongo-wait-and-run.sh:ro
        entrypoint: ['/bin/bash', '/mongo-wait-and-run.sh']
        networks:
            - videonet
        healthcheck:
            test: ['CMD', 'mongosh', '--eval', "db.adminCommand('ping')"]
            interval: 5s
            timeout: 3s
            retries: 10
    redis:
        image: redis:alpine
        container_name: redis
        restart: unless-stopped
        ports:
            - '${REDIS_PORT_INTERNAL}:${REDIS_PORT}'
        volumes:
            - redis_data:/data
        networks:
            - videonet
    localstack:
        container_name: localstack
        image: localstack/localstack
        restart: unless-stopped
        ports:
            - '4566:4566'
            - '4510-4559:4510-4559'
        environment:
            - SERVICES=events,sqs,sns
            - DEBUG=true
        volumes:
            - localstack_data:/var/lib/localstack
            - /var/run/docker.sock:/var/run/docker.sock
        networks:
            - videonet

networks:
    videonet:
        driver: bridge

volumes:
    db_data_users_shard_1:
    db_data_users_shard_2:
    db_data_videos:
    db_data_videos_replica:
    db_mongo_config_server:
    db_mongo_shard_1:
    db_mongo_shard_2:
    db_mongo_video_comments:
    redis_data:
    localstack_data:
