version: '3.8'

services:
    app-users:
        build:
            context: .
            dockerfile: docker/users-dockerfile
        ports:
            - '3000:3000'
        env_file:
            - .env.docker
        volumes:
            - .:/app
            - /app/node_modules
            - /app/dist
            - ${HOME}/.aws:/root/.aws:ro
        depends_on:
            db-users:
                condition: service_healthy
            localstack:
                condition: service_healthy
        networks:
            - videonet
    app-videos:
        build:
            context: .
            dockerfile: docker/videos-dockerfile
        ports:
            - '3001:3001'
        env_file:
            - .env.docker
        volumes:
            - .:/app
            - /app/node_modules
            - /app/dist
            - ${HOME}/.aws:/root/.aws:ro
        depends_on:
            db-videos:
                condition: service_healthy
            localstack:
                condition: service_healthy
        networks:
            - videonet
    db-users:
        image: postgres:15-alpine
        container_name: postgres-users
        restart: unless-stopped
        environment:
            - POSTGRES_USER=${USERS_DB_POSTGRES_USER}
            - POSTGRES_PASSWORD=${USERS_DB_POSTGRES_PASSWORD}
            - POSTGRES_DB=${USERS_DB_POSTGRES_NAME}
            - DB_REPLICA_USER=${USERS_DB_REPLICA_POSTGRES_USER}
            - DB_REPLICA_PASSWORD=${USERS_DB_REPLICA_POSTGRES_PASSWORD}
        ports:
            - '5432:5432'
        volumes:
            - db_data_users:/var/lib/postgresql/data
            - ./docker/replica-init.sh:/docker-entrypoint-initdb.d/replica-init.sh:ro
        networks:
            - videonet
        healthcheck:
            test:
                [
                    'CMD-SHELL',
                    'pg_isready -U ${USERS_DB_POSTGRES_USER} -d ${USERS_DB_POSTGRES_NAME} -h localhost || exit 1',
                ]
            interval: 5s
            timeout: 3s
            retries: 3
            start_period: 5s
    db-videos:
        image: postgres:15-alpine
        container_name: postgres-videos
        restart: unless-stopped
        environment:
            - POSTGRES_USER=${VIDEOS_DB_POSTGRES_USER}
            - POSTGRES_PASSWORD=${VIDEOS_DB_POSTGRES_PASSWORD}
            - POSTGRES_DB=${VIDEOS_DB_POSTGRES_NAME}
            - DB_REPLICA_USER=${VIDEOS_DB_REPLICA_POSTGRES_USER}
            - DB_REPLICA_PASSWORD=${VIDEOS_DB_REPLICA_POSTGRES_PASSWORD}
        ports:
            - '5434:5432'
        volumes:
            - db_data_videos:/var/lib/postgresql/data
            - ./docker/replica-init.sh:/docker-entrypoint-initdb.d/replica-init.sh:ro
        networks:
            - videonet
        healthcheck:
            test:
                [
                    'CMD-SHELL',
                    'pg_isready -U ${VIDEOS_DB_POSTGRES_USER} -d ${VIDEOS_DB_POSTGRES_NAME} -h localhost || exit 1',
                ]
            interval: 5s
            timeout: 3s
            retries: 3
            start_period: 5s
    db-users-replica:
        image: postgres:15-alpine
        container_name: postgres-users-replica
        restart: unless-stopped
        environment:
            - POSTGRES_USER=${USERS_DB_REPLICA_POSTGRES_USER}
            - POSTGRES_PASSWORD=${USERS_DB_REPLICA_POSTGRES_PASSWORD}
            - POSTGRES_DB=${USERS_DB_REPLICA_POSTGRES_NAME}
            - DB_HOST=db-users
            - DB_REPLICA_USER=${USERS_DB_REPLICA_POSTGRES_USER}
            - DB_REPLICA_PASSWORD=${USERS_DB_REPLICA_POSTGRES_PASSWORD}
            - PGDATA=/var/lib/postgresql/data/pgdata
        ports:
            - '5433:5432'
        volumes:
            - db_data_users_replica:/var/lib/postgresql/data/pgdata
            - ./docker/replica-setup.sh:/docker-entrypoint-initdb.d/replica-setup.sh:ro
        depends_on:
            db-users:
                condition: service_healthy
        networks:
            - videonet
        healthcheck:
            test:
                [
                    'CMD-SHELL',
                    'pg_isready -U ${USERS_DB_REPLICA_POSTGRES_USER} -d ${USERS_DB_REPLICA_POSTGRES_NAME} -h localhost || exit 1',
                ]
            interval: 5s
            timeout: 3s
            retries: 3
            start_period: 5s
    db-videos-replica:
        image: postgres:15-alpine
        container_name: postgres-videos-replica
        restart: unless-stopped
        environment:
            - POSTGRES_USER=${VIDEOS_DB_REPLICA_POSTGRES_USER}
            - POSTGRES_PASSWORD=${VIDEOS_DB_REPLICA_POSTGRES_PASSWORD}
            - POSTGRES_DB=${VIDEOS_DB_REPLICA_POSTGRES_NAME}
            - DB_HOST=db-videos
            - DB_REPLICA_USER=${VIDEOS_DB_REPLICA_POSTGRES_USER}
            - DB_REPLICA_PASSWORD=${VIDEOS_DB_REPLICA_POSTGRES_PASSWORD}
            - PGDATA=/var/lib/postgresql/data/pgdata
        ports:
            - '5435:5432'
        volumes:
            - db_data_videos_replica:/var/lib/postgresql/data/pgdata
            - ./docker/replica-setup.sh:/docker-entrypoint-initdb.d/replica-setup.sh:ro
        depends_on:
            db-videos:
                condition: service_healthy
        networks:
            - videonet
        healthcheck:
            test:
                [
                    'CMD-SHELL',
                    'pg_isready -U ${VIDEOS_DB_REPLICA_POSTGRES_USER} -d ${VIDEOS_DB_REPLICA_POSTGRES_NAME} -h localhost || exit 1',
                ]
            interval: 5s
            timeout: 3s
            retries: 3
            start_period: 5s
    redis:
        image: redis:alpine
        container_name: redis
        restart: unless-stopped
        ports:
            - '6379:6379'
        volumes:
            - redis_data:/data
        networks:
            - videonet
    localstack:
        container_name: localstack
        image: localstack/localstack
        restart: unless-stopped
        ports:
            - '4566:4566'
            - '4510-4559:4510-4559'
        environment:
            - SERVICES=events,sqs,sns
            - DEBUG=true
        volumes:
            - localstack_data:/var/lib/localstack
            - /var/run/docker.sock:/var/run/docker.sock
        networks:
            - videonet

networks:
    videonet:
        driver: bridge

volumes:
    db_data_users:
    db_data_users_replica:
    db_data_videos:
    db_data_videos_replica:
    redis_data:
    localstack_data:
