version: '3.8'

services:
    db:
        image: postgres:15-alpine
        container_name: postgres
        restart: unless-stopped
        environment:
            POSTGRES_USER: ${DB_USER}
            POSTGRES_PASSWORD: ${DB_PASSWORD}
            POSTGRES_DB: ${DB_NAME}
        ports:
            - '5432:5432'
        volumes:
            - db_data:/var/lib/postgresql/data
        networks:
            - videonet

networks:
    videonet:
        driver: bridge

volumes:
    db_data:
