version: '3.8'

services:
    app-users:
        build:
            context: .
            dockerfile: docker/users-dockerfile
        ports:
            - '3000:3000'
        env_file:
            - .env.docker
        volumes:
            - .:/app
            - /app/node_modules
            - /app/dist
            - ${HOME}/.aws:/root/.aws:ro
        depends_on:
            db-users-shard-1:
                condition: service_healthy
            db-users-shard-2:
                condition: service_healthy
            localstack:
                condition: service_healthy
        networks:
            - videonet
    app-videos:
        build:
            context: .
            dockerfile: docker/videos-dockerfile
        ports:
            - '3001:3001'
        env_file:
            - .env.docker
        volumes:
            - .:/app
            - /app/node_modules
            - /app/dist
            - ${HOME}/.aws:/root/.aws:ro
        depends_on:
            db-videos:
                condition: service_healthy
            localstack:
                condition: service_healthy
        networks:
            - videonet
    db-users-shard-1:
        image: postgres:15-alpine
        container_name: postgres-users-shard-1
        restart: unless-stopped
        environment:
            - POSTGRES_USER=${USERS_POSTGRES_DB_SHARD_1_USER}
            - POSTGRES_PASSWORD=${USERS_POSTGRES_DB_SHARD_1_PASSWORD}
            - POSTGRES_DB=${USERS_POSTGRES_DB_SHARD_1_NAME}
        ports:
            - '5432:5432'
        volumes:
            - db_data_users_shard_1:/var/lib/postgresql/data
        networks:
            - videonet
        healthcheck:
            test:
                [
                    'CMD-SHELL',
                    'pg_isready -U ${USERS_POSTGRES_DB_SHARD_1_USER} -d ${USERS_POSTGRES_DB_SHARD_1_NAME} -h localhost || exit 1',
                ]
            interval: 5s
            timeout: 3s
            retries: 3
            start_period: 5s
    db-users-shard-2:
        image: postgres:15-alpine
        container_name: postgres-users-shard-2
        restart: unless-stopped
        environment:
            - POSTGRES_USER=${USERS_POSTGRES_DB_SHARD_2_USER}
            - POSTGRES_PASSWORD=${USERS_POSTGRES_DB_SHARD_2_PASSWORD}
            - POSTGRES_DB=${USERS_POSTGRES_DB_SHARD_2_NAME}
        ports:
            - '5433:5432'
        volumes:
            - db_data_users_shard_2:/var/lib/postgresql/data
        networks:
            - videonet
        healthcheck:
            test:
                [
                    'CMD-SHELL',
                    'pg_isready -U ${USERS_POSTGRES_DB_SHARD_2_USER} -d ${USERS_POSTGRES_DB_SHARD_2_NAME} -h localhost || exit 1',
                ]
            interval: 5s
            timeout: 3s
            retries: 3
            start_period: 5s
    db-videos:
        image: postgres:15-alpine
        container_name: postgres-videos
        restart: unless-stopped
        environment:
            - POSTGRES_USER=${VIDEOS_POSTGRES_DB_USER}
            - POSTGRES_PASSWORD=${VIDEOS_POSTGRES_DB_PASSWORD}
            - POSTGRES_DB=${VIDEOS_POSTGRES_DB_NAME}
            - DB_REPLICA_USER=${VIDEOS_POSTGRES_DB_REPLICA_USER}
            - DB_REPLICA_PASSWORD=${VIDEOS_POSTGRES_DB_REPLICA_PASSWORD}
        ports:
            - '5434:5432'
        volumes:
            - db_data_videos:/var/lib/postgresql/data
            - ./docker/replica-init.sh:/docker-entrypoint-initdb.d/replica-init.sh:ro
        networks:
            - videonet
        healthcheck:
            test:
                [
                    'CMD-SHELL',
                    'pg_isready -U ${VIDEOS_POSTGRES_DB_USER} -d ${VIDEOS_POSTGRES_DB_NAME} -h localhost || exit 1',
                ]
            interval: 5s
            timeout: 3s
            retries: 3
            start_period: 5s
    db-videos-replica:
        image: postgres:15-alpine
        container_name: postgres-videos-replica
        restart: unless-stopped
        environment:
            - POSTGRES_USER=${VIDEOS_POSTGRES_DB_REPLICA_USER}
            - POSTGRES_PASSWORD=${VIDEOS_POSTGRES_DB_REPLICA_PASSWORD}
            - POSTGRES_DB=${VIDEOS_POSTGRES_DB_REPLICA_NAME}
            - DB_HOST=db-videos
            - DB_REPLICA_USER=${VIDEOS_POSTGRES_DB_REPLICA_USER}
            - DB_REPLICA_PASSWORD=${VIDEOS_POSTGRES_DB_REPLICA_PASSWORD}
            - PGDATA=/var/lib/postgresql/data/pgdata
        ports:
            - '5435:5432'
        volumes:
            - db_data_videos_replica:/var/lib/postgresql/data/pgdata
            - ./docker/replica-setup.sh:/docker-entrypoint-initdb.d/replica-setup.sh:ro
        depends_on:
            db-videos:
                condition: service_healthy
        networks:
            - videonet
        healthcheck:
            test:
                [
                    'CMD-SHELL',
                    'pg_isready -U ${VIDEOS_POSTGRES_DB_REPLICA_USER} -d ${VIDEOS_POSTGRES_DB_REPLICA_NAME} -h localhost || exit 1',
                ]
            interval: 5s
            timeout: 3s
            retries: 3
            start_period: 5s
    db-video-comments:
        image: mongo:7.0
        container_name: mongo-video-comments
        restart: unless-stopped
        environment:
            - MONGO_INITDB_ROOT_USERNAME=${VIDEOS_COMMENT_MONGO_DB_USER}
            - MONGO_INITDB_ROOT_PASSWORD=${VIDEOS_COMMENT_MONGO_DB_PASSWORD}
            - MONGO_INITDB_DATABASE=${VIDEOS_COMMENT_MONGO_DB_NAME}
        ports:
            - '27017:27017'
        volumes:
            - db_data_video_comments:/data/db
        networks:
            - videonet
        healthcheck:
            test: >
                mongosh --username ${VIDEOS_COMMENT_MONGO_DB_USER} \
                        --password ${VIDEOS_COMMENT_MONGO_DB_PASSWORD} \
                        --authenticationDatabase admin \
                        --eval "db.adminCommand('ping')" || exit 1
            interval: 5s
            timeout: 3s
            retries: 3
            start_period: 5s
    redis:
        image: redis:alpine
        container_name: redis
        restart: unless-stopped
        ports:
            - '6379:6379'
        volumes:
            - redis_data:/data
        networks:
            - videonet
    localstack:
        container_name: localstack
        image: localstack/localstack
        restart: unless-stopped
        ports:
            - '4566:4566'
            - '4510-4559:4510-4559'
        environment:
            - SERVICES=events,sqs,sns
            - DEBUG=true
        volumes:
            - localstack_data:/var/lib/localstack
            - /var/run/docker.sock:/var/run/docker.sock
        networks:
            - videonet

networks:
    videonet:
        driver: bridge

volumes:
    db_data_users_shard_1:
    db_data_users_shard_2:
    db_data_videos:
    db_data_videos_replica:
    db_data_video_comments:
    redis_data:
    localstack_data:
