releaseVersion: '0.0.0' # Updated by CI/CD pipeline

app:
    name: videomatt-videos
    containerName: videomatt-videos-container
    namespace: vittospace
    port: 3001

deployment:
    name: videomatt-videos-deployment
    replicas: 3

service:
    name: videomatt-videos-service
    blue: videomatt-videos-active
    green: videomatt-videos-preview
    type: LoadBalancer
    port: 3001

configmap:
    name: videomatt-videos-configmap

secret:
    name: videomatt-videos-secret
