releaseVersion: '0.0.0' # Updated by CI/CD pipeline

app:
    name: videomatt-users
    containerName: videomatt-users-container
    namespace: vittospace
    port: 3001

deployment:
    name: videomatt-users-deployment
    replicas: 1

service:
    name: videomatt-users-service
    blue: videomatt-users-active
    green: videomatt-users-preview
    type: NodePort
    port: 3001
    nodePort: 30001

configmap:
    name: videomatt-users-configmap

secret:
    name: videomatt-users-secret
