apiVersion: v1
kind: ConfigMap
metadata:
    name: {{ .Values.configmap.name }}
    namespace: {{ .Values.app.namespace }}
data:
    NODE_ENV: prod
    USERS_PORT: '3000'
    USERS_POSTGRES_DB_SHARD_1_HOST: videomatt-users-postgres-shard-1-postgresql
    USERS_POSTGRES_DB_SHARD_1_PORT: '5432'
    USERS_POSTGRES_DB_SHARD_1_SHARD_NAME: shard1
    USERS_POSTGRES_DB_SHARD_2_HOST: videomatt-users-postgres-shard-2-postgresql
    USERS_POSTGRES_DB_SHARD_2_PORT: '5432'
    USERS_POSTGRES_DB_SHARD_2_SHARD_NAME: shard2
    AWS_REGION: us-east-1
    AWS_SNS_ENDPOINT: http://videomatt-localstack:4566
    AWS_SQS_ENDPOINT: http://videomatt-localstack:4566
    AWS_EVENT_BRIDGE_ENDPOINT: http://videomatt-localstack:4566
    SQS_USER_CREATED_QUEUE_URL: http://videomatt-localstack:4566/000000000000/videomatt_users_1_event_user_created
    SQS_VIDEO_CREATED_QUEUE_URL: http://videomatt-localstack:4566/000000000000/videomatt_videos_1_event_video_created
    SNS_VIDEO_TOPIC_ARN: arn:aws:sns:us-east-1:000000000000:videomatt_videos
    EVENT_BRIDGE_USER_TOPIC_ARN: arn:aws:sns:us-east-1:000000000000:videomatt_users
